[build]
  # Build command
  command = "npm run build"
  
  # Directory to publish (Vite builds to 'dist')
  publish = "dist"

[build.environment]
  # Node.js version and production environment variables
  NODE_VERSION = "18"
  VITE_API_URL = "https://infrastructure-management-system-production.up.railway.app/api"
  VITE_APP_NAME = "Système de Gestion d'Infrastructure"
  VITE_APP_VERSION = "1.0.0"

# SPA routing - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://infrastructure-management-system-production.up.railway.app;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache service worker
[[headers]]
  for = "/sw.js"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
