// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://jccdswfwbovhhkydtcsr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImpjY2Rzd2Z3Ym92aGhreWR0Y3NyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNjI2NTUsImV4cCI6MjA2NzczODY1NX0.PEuf_4-T0gAXqE1XkHpq_mVI3tH_w6DZh0lf3566MlI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});